@extends('layouts.admin')
@section('title',$item->exists ? 'Edit content' : 'Add content')
@section('content')
<div class="admin-title"><div><a class="back-link" href="{{ route('admin.index') }}">← Back to content</a><h1>{{ $item->exists ? 'Edit content' : 'Add content' }}</h1></div></div>
<form class="admin-form" method="post" enctype="multipart/form-data" action="{{ $item->exists ? route('admin.content.update',$item) : route('admin.content.store') }}">@csrf @if($item->exists)@method('PUT')@endif
    @if($errors->any())<div class="form-error"><strong>Please correct the form:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <fieldset><legend>Core information</legend><div class="field-row"><label>Content type *<select name="type" required>@foreach(\App\Models\ContentItem::TYPES as $type)<option value="{{ $type }}" @selected(old('type',$item->type)===$type)>{{ str_replace('_',' ',ucfirst($type)) }}</option>@endforeach</select></label><label>Reference code<input name="reference_code" value="{{ old('reference_code',$item->reference_code) }}" placeholder="e.g. D2.1"></label></div><label>Title *<input name="title" value="{{ old('title',$item->title) }}" required></label><label>Short description<textarea name="excerpt" rows="3">{{ old('excerpt',$item->excerpt) }}</textarea></label><label>Full content<textarea name="body" rows="12">{{ old('body',$item->body) }}</textarea></label></fieldset>
    <fieldset><legend>Publication details</legend><div class="field-row"><label>Status *<select name="status">@foreach(['draft','forthcoming','published','completed'] as $status)<option value="{{ $status }}" @selected(old('status',$item->status ?: 'draft')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></label><label>Category<input name="category" value="{{ old('category',$item->category) }}"></label></div><div class="field-row"><label>Responsible partner<input name="partner" value="{{ old('partner',$item->partner) }}"></label><label>Publication date<input type="date" name="published_at" value="{{ old('published_at',optional($item->published_at)->format('Y-m-d')) }}"></label></div><div class="field-row"><label>Event date and time<input type="datetime-local" name="event_date" value="{{ old('event_date',optional($item->event_date)->format('Y-m-d\TH:i')) }}"></label><label>Sort order<input type="number" name="sort_order" min="0" value="{{ old('sort_order',$item->sort_order ?: 0) }}"></label></div><label class="check-field"><input type="checkbox" name="is_public" value="1" @checked(old('is_public',$item->is_public))> Make this item publicly visible</label></fieldset>
    <fieldset><legend>Files and links</legend><div class="field-row"><label>Document <small>PDF, Word, Excel, PowerPoint or ZIP · max 20 MB</small><input type="file" name="document">@if($item->file_path)<span>Current file: {{ basename($item->file_path) }}</span>@endif</label><label>Cover image <small>JPG, PNG or WebP · max 5 MB</small><input type="file" name="image" accept="image/jpeg,image/png,image/webp">@if($item->image_path)<span>Current image: {{ basename($item->image_path) }}</span>@endif</label></div><label>External URL<input type="url" name="external_url" value="{{ old('external_url',$item->external_url) }}" placeholder="https://"></label></fieldset>
    <button class="button" type="submit">{{ $item->exists ? 'Save changes' : 'Create content' }}</button>
</form>
@endsection
