<?php

return [
    'grant_agreement' => 'GAP-101304748',
    'linkedin' => 'https://www.linkedin.com/company/valuemapproject/',

    'work_packages' => [
        [
            'number' => '01',
            'title' => 'Management and Coordination',
            'lead' => 'InnoStars',
            'duration' => 'Month 1–Month 18',
            'description' => 'WP1 ensures the effective management, coordination and implementation of the project.',
            'activities' => ['Overall project coordination', 'Administrative and financial management', 'Quality assurance and risk management', 'Consortium communication and cooperation', 'Monitoring of project progress and deliverables'],
            'outputs' => 'Management framework, quality assurance, risk monitoring and coordinated delivery.',
            'start' => 1,
            'end' => 18,
        ],
        [
            'number' => '02',
            'title' => 'European Landscape Analysis',
            'lead' => 'CoLAB TRIALS',
            'duration' => 'Month 1–Month 4',
            'description' => 'WP2 establishes a European evidence base on health data business models, initiatives and practices.',
            'activities' => ['European desk research', 'Mapping relevant initiatives and approaches', 'Pan-European stakeholder survey', 'Analysis of business models and value-sharing practices', 'Identification of barriers, opportunities and transferable experience'],
            'outputs' => 'European Landscape Report',
            'start' => 1,
            'end' => 4,
        ],
        [
            'number' => '03',
            'title' => 'Regional Assessment',
            'lead' => 'Consejería de Sanidad de la Comunidad de Madrid',
            'duration' => 'Month 3–Month 10',
            'description' => 'WP3 examines the characteristics, needs and development opportunities of regional health data ecosystems.',
            'activities' => ['National and regional stakeholder roundtables', 'Targeted stakeholder interviews', 'Regional use-case analysis', 'SWOT and PESTEL assessments', 'Analysis of regional health data business models', 'Interregional synthesis and knowledge exchange'],
            'outputs' => 'Regional Assessment Reports and Interregional Synthesis Report',
            'start' => 3,
            'end' => 10,
        ],
        [
            'number' => '04',
            'title' => 'Joint Action Planning',
            'lead' => 'Institut Català de la Salut',
            'duration' => 'Month 10–Month 18',
            'description' => 'WP4 translates European and regional findings into shared priorities and practical actions.',
            'activities' => ['Establishing an Interregional Health Data Business Models Advisory Board', 'Developing actionable recommendations', 'Identifying and prioritising joint actions', 'Preparing the Multi-annual Joint Action Plan', 'Developing the Implementation Toolkit'],
            'outputs' => 'Multi-annual Joint Action Plan and Implementation Toolkit',
            'start' => 10,
            'end' => 18,
        ],
        [
            'number' => '05',
            'title' => 'Communication, Dissemination and Exploitation',
            'lead' => 'Verlab Institute',
            'duration' => 'Month 1–Month 18',
            'description' => 'WP5 ensures that VALUEMAP knowledge, activities and results reach relevant stakeholders and wider European discussions.',
            'activities' => ['Website development and maintenance', 'Communication and dissemination planning', 'News, newsletters and digital communication', 'Stakeholder engagement and project events', 'Communication materials and media activities', 'Dissemination, exploitation and sustainability planning'],
            'outputs' => 'Communication resources, stakeholder activities, result dissemination and sustainability planning',
            'start' => 1,
            'end' => 18,
        ],
    ],

    'partners' => [
        ['initials' => 'IS', 'name' => 'InnoStars', 'country' => 'Hungary', 'location' => 'Hungary', 'latitude' => 47.4979, 'longitude' => 19.0402, 'role' => 'Project Coordinator and WP1 Lead', 'description' => 'Coordinates the project and supports collaboration between European health innovation ecosystems, stakeholders and institutions.', 'url' => 'https://innostars.org/'],
        ['initials' => 'ICS', 'name' => 'Institut Català de la Salut', 'country' => 'Spain', 'location' => 'Barcelona', 'latitude' => 41.3874, 'longitude' => 2.1686, 'role' => 'Beneficiary and WP4 Lead', 'description' => 'Contributes healthcare-system expertise and leads the development of joint actions, recommendations and implementation tools.', 'url' => 'https://ics.gencat.cat/ca/lics/'],
        ['initials' => 'CT', 'name' => 'CoLAB TRIALS', 'country' => 'Portugal', 'location' => 'Portugal', 'latitude' => 39.5, 'longitude' => -8.0, 'role' => 'Beneficiary and WP2 Lead', 'description' => 'Leads the European landscape analysis and contributes expertise in research, innovation and health data-related approaches.', 'url' => 'https://colabtrials.pt/'],
        ['initials' => 'KI', 'name' => 'Karolinska Institutet', 'country' => 'Sweden', 'location' => 'Stockholm', 'latitude' => 59.3293, 'longitude' => 18.0686, 'role' => 'Beneficiary', 'description' => 'Contributes expertise in research, digital health and health data-related regulatory and innovation contexts.', 'url' => 'https://ki.se/en'],
        ['initials' => 'FPS', 'name' => 'Fundación Pública Andaluza Progreso y Salud', 'country' => 'Spain', 'location' => 'Seville', 'latitude' => 37.3891, 'longitude' => -5.9845, 'role' => 'Beneficiary', 'description' => 'Contributes expertise in public health research and innovation and supports advisory and joint planning activities.', 'url' => 'https://juntadeandalucia.es/organismos/fps.html'],
        ['initials' => 'VI', 'name' => 'Verlab Institute', 'country' => 'Bosnia and Herzegovina', 'location' => 'Sarajevo', 'latitude' => 43.8563, 'longitude' => 18.4131, 'role' => 'Beneficiary and WP5 Lead', 'description' => 'Leads communication, dissemination and exploitation and contributes digital health and biomedical engineering expertise.', 'url' => 'https://verlabinstitute.com/'],
        ['initials' => 'CM', 'name' => 'Consejería de Sanidad de la Comunidad de Madrid', 'country' => 'Spain', 'location' => 'Madrid', 'latitude' => 40.4168, 'longitude' => -3.7038, 'role' => 'Beneficiary and WP3 Lead', 'description' => 'Leads regional assessment activities and contributes public-sector and healthcare-system perspectives.', 'url' => 'https://www.comunidad.madrid/centros/consejeria-sanidad'],
        ['initials' => 'FI', 'name' => 'Fundación para la Investigación e Innovación Biosanitaria de Atención Primaria', 'country' => 'Spain', 'location' => 'Madrid', 'latitude' => 40.4168, 'longitude' => -3.7038, 'map_offset_x' => 38, 'map_offset_y' => -14, 'role' => 'Affiliated Partner', 'description' => 'Contributes expertise in primary healthcare, research and innovation and supports stakeholder engagement.', 'url' => 'https://fiibap.es/'],
        ['initials' => 'TK', 'name' => 'Takeda Products Ireland Ltd.', 'country' => 'Ireland', 'location' => 'Citywest, Dublin', 'latitude' => 53.286, 'longitude' => -6.426, 'role' => 'Associated Partner', 'description' => 'Contributes an industry and pharmaceutical perspective on health data, innovation and sustainable business models.', 'url' => 'https://www.takeda.com/'],
    ],

    'stakeholders' => [
        ['Healthcare providers and data owners', 'Hospitals, healthcare organisations and institutions responsible for collecting, managing and providing access to health data.'],
        ['Regulators and public authorities', 'Public bodies, policymakers and regulatory stakeholders shaping the governance, access and responsible use of health data.'],
        ['SMEs and start-ups', 'Innovative companies developing new products, services and solutions based on health data.'],
        ['Pharmaceutical and technology industry', 'Industry stakeholders contributing expertise in research, development, digital technologies and health innovation.'],
        ['Researchers and academic institutions', 'Universities, research organisations and experts advancing knowledge and new approaches to health data use.'],
        ['Citizens and patient organisations', 'People and organisations representing the interests, rights, expectations and needs of individuals whose data supports research and innovation.'],
    ],

    'results' => [
        ['European Landscape Report', 'A structured overview of health data business models, initiatives, practices, opportunities and challenges across Europe.'],
        ['Regional Assessment Reports', 'Evidence-based assessments of selected regional ecosystems, stakeholder needs, barriers, opportunities and use cases.'],
        ['Interregional Synthesis Report', 'A consolidated analysis highlighting common challenges, transferable practices and cooperation opportunities.'],
        ['Actionable Recommendations', 'Practical recommendations on governance, access, sustainability and value-sharing conditions.'],
        ['Multi-annual Joint Action Plan', 'A strategic framework identifying priorities and actions for stronger cooperation and sustainable business models.'],
        ['Implementation Toolkit', 'Practical guidance, methods and resources for translating project recommendations into action.'],
        ['Cooperation and Funding Opportunities', 'A matrix connecting priorities with initiatives, networks, programmes and funding opportunities.'],
    ],
];
