@extends('layouts.app')
@section('title', 'About the project')
@section('description', 'Discover ValueMap’s objective, expected contribution, results and long-term impact for European health data ecosystems.')
@section('content')
<header class="page-hero"><p class="eyebrow">About ValueMap</p><h1>Seeing the whole ecosystem changes <em>what is possible.</em></h1><p>ValueMap is a Horizon Europe research project focused on understanding how European health data ecosystems create value — and how stronger connections can make that value more equitable, trusted and useful.</p></header>
<section class="section split-feature"><div><p class="eyebrow">The context</p><h2>Rich in data.<br><em>Fragmented in practice.</em></h2></div><div class="prose"><p>Across Europe, health data initiatives operate within different regional, legal, institutional and technological realities. Valuable knowledge exists, but it is often difficult to compare, connect and translate into coordinated action.</p><p>ValueMap creates a common view of these ecosystems: the actors involved, the resources they hold, the relationships between them and the conditions that enable data to contribute to better health outcomes and wider public value.</p><div class="draft-note">This page is prepared for the full consortium-approved project description. The current copy is an editorial draft based on the initial brief.</div></div></section>
<section class="section objective-panel"><p class="eyebrow">Main objective</p><div><span class="objective-number">01</span><h2>Build an evidence-based map of European health data ecosystems and turn that knowledge into practical pathways for collaboration and value creation.</h2></div></section>
<section class="section outcomes-section"><div class="section-heading"><p class="eyebrow">Expected contribution</p><h2>Knowledge that can <em>move systems.</em></h2></div><div class="outcome-grid"><article><span>01</span><h3>A shared evidence base</h3><p>Comparable insights into ecosystem actors, assets, relationships, barriers and enablers across participating regions.</p></article><article><span>02</span><h3>Actionable pathways</h3><p>Practical guidance for strengthening how health data ecosystems collaborate and generate public value.</p></article><article><span>03</span><h3>Connected communities</h3><p>Deeper exchange between providers, authorities, researchers, companies and citizen or patient groups.</p></article><article><span>04</span><h3>Transferable learning</h3><p>Methods and resources designed to remain useful to other regions beyond the project consortium.</p></article></div></section>
<section class="impact-band"><p class="eyebrow">Long-term impact</p><h2>More coherent ecosystems.<br>Better use of health data.<br><em>Greater public value.</em></h2><a class="button button-lime" href="{{ route('ecosystem') }}">Meet the ecosystem ↗</a></section>
@endsection
